# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alanna Joanne
email: alanna@alannajoanne.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance Digital Producer. Also known as Producer on the amazing Shoots Official team. Oftentimes, I can be found curled up in a cozy chair writing lines of poetry ğŸšğŸŒ± 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alannajoanne.com" # the base hostname & protocol for your site
twitter_username: alannajoanne11
github_username:  alannajoanne
shareImage: "http://alannajoanne.assets/images/alannajoanne-shoots.jpg"
contactEmail: alanna@alannajoanne.com

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
